# Generated by Django 4.2.7 on 2026-02-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('action', models.TextField()),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('trend', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_pairs', models.JSONField(default=list)),
                ('risk_tolerance', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
