# Generated by Django 6.0.2 on 2026-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_agentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('var_95', models.DecimalField(blank=True, decimal_places=5, help_text='Value at Risk at 95% confidence', max_digits=10, null=True)),
                ('var_99', models.DecimalField(blank=True, decimal_places=5, help_text='Value at Risk at 99% confidence', max_digits=10, null=True)),
                ('cvar', models.DecimalField(blank=True, decimal_places=5, help_text='Conditional Value at Risk (Expected Shortfall)', max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Sharpe Ratio', max_digits=5, null=True)),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=5, help_text='Maximum Drawdown as percentage', max_digits=10, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=5, help_text='Annualized Volatility', max_digits=10, null=True)),
                ('atr', models.DecimalField(blank=True, decimal_places=5, help_text='Average True Range', max_digits=10, null=True)),
                ('atr_stop_loss', models.DecimalField(blank=True, decimal_places=5, help_text='ATR-based Stop Loss', max_digits=10, null=True)),
                ('atr_take_profit', models.DecimalField(blank=True, decimal_places=5, help_text='ATR-based Take Profit', max_digits=10, null=True)),
                ('position_size', models.DecimalField(blank=True, decimal_places=5, help_text='Recommended Position Size (lots)', max_digits=10, null=True)),
                ('risk_per_trade', models.DecimalField(blank=True, decimal_places=2, help_text='Risk per trade as percentage', max_digits=5, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Risk/Reward Ratio', max_digits=5, null=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Overall Risk Score (0-100)', max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], default='MEDIUM', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
